### ISSUE TITLE
Standardize file names

### ISSUE THREAD

**Issue by tux3** [Tox/Sounds#5]
It would be pretty cool if clients could automatically use custom sound packs, and for that we need a standard organization for the sound files.

It's already organized in subfolders (Misc, Call Sounds, ...), but instead it would be more useful to define standard file names like Ringtone.flac, NewMessage.flac, etc.

**Comment by Zer0-One** [comment]
That seems reasonable, but requires that we come up with a list of all possible sounds we might need, and this involves creating descriptions for each, in order to let sound designers know what they're working on. 

One issue with this is that there might be a sound that we would like that we haven't thought of yet. So we should have some way of letting a contributor suggest new names.

**Comment by lehitoskin** [comment]
What we could do is have a base set of "expected" sounds that are most used by clients and then the other sounds, which other clients may or may not use, can be added but not be expected. This way users could install new sounds and still have the most obvious ones covered.

For example:
- sign in
- sign out
- new message
- incoming call
- outgoing call

P.S. Requiring the files be FLAC is a bad idea because there are some audio libraries that don't support it. A common name structure could be fine, but depending on a single format would be a bad idea.

**Comment by Zer0-One** [comment]
@lehitoskin We only require lossless encoding, not any codec in particular (like FLAC). The reason for it is that it's trivial to re-encode the audio using whatever kind of lossy compression you want.

**Comment by RowenStipe** [comment]
I had an idea for this, what instead of relying on a user to put the files in their exact proper place the sound packs use a JSON file that they could point the proper files for the proper sound event.

Example mock up:

``` json
{
    "PackName":"Example Pack",
    "Author(S)":["This Guy","Other Dude"],
    "Source":"http://www.example.tld",
    "Licence":"CC-V4",
    "Description":"A basic description of the pack.",
    "Notifications": 
    {
        "NewMessage":"./dir/to/file.flac",
        "NewFriend":"./dir/to/file.flac",
        "UserOnline":"./dir/to/file.flac",
        "UserOffline":"./dir/to/file.flac"
    },
    "Call":
    {
        "DialTone":{"./dir/to/file.flac":15},
        "IncommingCall":{"./dir/to/file.flac":15},
        "IncommingVideo":{"./dir/to/file.flac":8}
    },
    "FileTransfer":
    {
        "Incomming":"./dir/to/file.flac",
        "Sucess":"./dir/to/file.flac",
        "Fail":"./dir/to/file.flac",
        "Resume":"./dir/to/file.flac"
    },
    "Group":
    {
        "Invite":"./dir/to/file.flac",
        "MemberJoin":"./dir/to/file.flac",
        "MemberLeave":"./dir/to/file.flac",
        "TitleChange":"./dir/to/file.flac",
        "IncommingCall":{"./dir/to/file.flac":10},
        "UserLeftCall":"./dir/to/file.flac"
    }
}
```

Events that would obviously repeat such as `"IncommingCall":{"./dir/to/file.flac":15}` would use the number in `{"./dir/to/file.flac":15}` to denote how many times that file repeats it's self. This adds some customization that relies on the creator to determine the pause between repeats if any.

**Comment by Zer0-One** [comment]
@tux3 @stal888 @JFreegman @Grayhatter thoughts on @RowenStipe 's suggestion above?

IMO, it introduces too much unnecessary complexity. Having standard names will accomplish the same thing, but without forcing client devs to implement json. Instead of relying on files being in their proper place, you're now relying on someone to update a json file pointing to their proper place.

Even in the case where you want to split the sound files up into different directories, there aren't enough sounds that a simple recursive search wouldn't do the job of locating them.

**Comment by GrayHatter** [comment]
uTox has no current roadmap for json

**Comment by stal888** [comment]
~~I have an essay to write~~ Let's just use filenames.

**Comment by tux3** [comment]
I don't see the point of the JSON file, you're just adding one level of indirection, but the sound names still need to be standardized.
And the number of repetitions idea wouldn't really work for qTox, for sounds like ringtones we play then on repeat until we have a reason to stop, not a fixed number of repeats.

**Comment by Zer0-One** [comment]
I'm going to work on this sometime soon, but if anyone wants to get a head start, please feel free

**Comment by RowenStipe** [comment]
Basing this idea off of the already existing requirement of a basic file structure for inclusion into this repo, and the fact I had to come up with some kinda name for the JASON example

```
=Call
    |-DialTone.LMFN
    |-Incomming(Video/Call).LMFN
    |-Drop.LMFN
=Group
    |-NewMember.LMFN
    |-MemberLeft.LMFN
    \-NameChange.LMFN
    =Call
        |-DialTone.LMFN
        |-Incomming(Video/Call).LMFN
        |-MemberJoin.LMFN
        |-MemberLeave.LMFN
        |-Drop.LMFN
=Notification
    |-NewMessage.LMFN
    |-NewInvite.LMFN
    |-FriendOnline.LMFN
    |-FriendOffline.LMFN
    |-Error.LMFN
    =FileTransfer
        |-Inncomming.LMFN
        |-Sucess.LMFN
        |-Fail.LMFN
        \-Resume.LMFN

KEY:
(Video/Call) = optional differentiation 
\- = optional includement
=Call = Folder named Call

KEY:
(Video/Call) = optional differentiation 
\- = optional includement
=Call = Folder named Call
.LMFN = Lossless Media File Name
```

Based off of this structure the files directory reads as:
`PackName/Group/Call/DialTone.LMFN`

Thoughts anyone?

**Comment by Zer0-One** [comment]
https://github.com/Tox/Sounds/commit/614a3151bcb3cfe9d3f22012fa533f14a78fe123

Everyone happy with this?

**Comment by alexbakker** [comment]
Looks good to me

**Comment by tux3** [comment]
Sounds good.

**Comment by stal888** [comment]
I'm not sold on the file structure... I'd do this:

```
=Ringtone
    |-IncomingVideo.ext
    |-IncomingAudio.ext
    |-OutgoingVideo.ext
    |-OutgoingAudio.ext
=Notification
    |-CallDrop.ext
    |-GeneralError.ext
    |-ContactOffline.ext
    |-ContactOnline.ext
    |-Invite.ext
    |-Message.ext
    |-ImportantMessage.ext
    =FileTransfer
        |-Failure.ext
        |-Incoming.ext
        |-Resume.ext
        |-Success.ext
    =Group
        |-Leave.ext
        |-NameChange.ext
        |-Join.ext
```

**Comment by Zer0-One** [comment]
@stal888 What is an "important message"? How does a client distinguish an important message from a regular message? Also, why are _FileTransfer_ and _Group_ under _Notification_ while _Ringtone_ isn't?

**Comment by stal888** [comment]
As I said in IRC, ringtones play continuously.

Clients can decide what messages are important, but I recommend "mentioning your name" as the standard criteria

**Comment by GrayHatter** [comment]
:+1:  to @stal888's suggestion. that's how they'd be sorted on a phone

**Comment by RowenStipe** [comment]
:shipit: @stal888's suggestion looks good to me as well.

**Comment by Zer0-One** [comment]
The README has been updated. @Rotkaermota and @RowenStipe , if you could both please update your sound collections accordingly, we'd appreciate it.
